### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by Lunatik934** [Dablakbandit/Core#2]
hey its not work with 1.8 version

[23:47:59 INFO]: [Bank] Unknown save type in config, switching to SQLLITE
[23:47:59 ERROR]: ENTITY_PLAYER_LEVELUP initializing Bank v3.0.5 (Is it up to date?)
java.lang.NoSuchFieldError: ENTITY_PLAYER_LEVELUP
        at me.dablakbandit.bank.SoundConfiguration.<clinit>(SoundConfiguration.java:16) ~[?:?]
        at me.dablakbandit.bank.BankPlugin.onLoad(BankPlugin.java:88) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[23:47:59 INFO]: [Core] Enabling Core v0.1.7

**Comment by Dablakbandit** [comment]
Go into your sounds.yml and change all your ENTITY_PLAYER_LEVELUP to LEVEL_UP

Hope this helps, you can view other sounds for 1.8.8 here: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html

**Comment by Lunatik934** [comment]
where is sounds.yml ?
